"""init tables

Revision ID: 573453833d2b
Revises: 0001_schemas
Create Date: 2026-08-05 02:11:44.820796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '573453833d2b'
down_revision: Union[str, None] = '0001_schemas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_data_registry'
    )
    op.create_index(op.f('ix_app_data_registry_data_sources_name'), 'data_sources', ['name'], unique=True, schema='app_data_registry')
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_data_registry'
    )
    op.create_index(op.f('ix_app_data_registry_services_name'), 'services', ['name'], unique=True, schema='app_data_registry')
    op.create_table('dim_data_sets_verified',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('hash_sum', sa.String(length=64), autoincrement=False, nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('period', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hash_sum'),
    schema='app_datasets'
    )
    op.create_table('downloaded_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('dest_path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'dest_path', name='uq_downloaded_url_dest'),
    schema='app_ecomru'
    )
    op.create_index('idx_downloaded_status', 'downloaded_files', ['status'], unique=False, schema='app_ecomru')
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('report_updated_at', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', 'period', 'report_updated_at', 'report_type', name='uq_notification_entity_period'),
    schema='app_ecomru'
    )
    op.create_index('idx_notification_log_lookup', 'notification_log', ['entity', 'period', 'report_updated_at', 'report_type'], unique=False, schema='app_ecomru')
    op.create_index(op.f('ix_app_ecomru_notification_log_entity'), 'notification_log', ['entity'], unique=False, schema='app_ecomru')
    op.create_table('processing_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('source_updated_at', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_ecomru'
    )
    op.create_index(op.f('ix_app_ecomru_processing_groups_entity'), 'processing_groups', ['entity'], unique=False, schema='app_ecomru')
    op.create_index(op.f('ix_app_ecomru_processing_groups_status'), 'processing_groups', ['status'], unique=False, schema='app_ecomru')
    op.create_table('file_download_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_file_manager'
    )
    op.create_table('schema_extraction_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_file_manager'
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_normalized', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash'),
    schema='app_link'
    )
    op.create_index('idx_links_url_hash', 'links', ['url_hash'], unique=False, schema='app_link')
    op.create_index('idx_links_url_normalized', 'links', ['url_normalized'], unique=False, schema='app_link')
    op.create_table('mail_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_mail'
    )
    op.create_index(op.f('ix_app_mail_mail_tasks_status'), 'mail_tasks', ['status'], unique=False, schema='app_mail')
    op.create_index(op.f('ix_app_mail_mail_tasks_task_id'), 'mail_tasks', ['task_id'], unique=True, schema='app_mail')
    op.create_index(op.f('ix_app_mail_mail_tasks_to_email'), 'mail_tasks', ['to_email'], unique=False, schema='app_mail')
    op.create_table('memory_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('rss_mb', sa.Float(), nullable=False),
    sa.Column('threshold_mb', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_monitor'
    )
    op.create_index('idx_mem_alerts_app_level', 'memory_alerts', ['app_name', 'level'], unique=False, schema='app_monitor')
    op.create_index('idx_mem_alerts_ts', 'memory_alerts', ['fired_at'], unique=False, schema='app_monitor')
    op.create_index(op.f('ix_app_monitor_memory_alerts_app_name'), 'memory_alerts', ['app_name'], unique=False, schema='app_monitor')
    op.create_table('memory_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('rss_mb', sa.Float(), nullable=False),
    sa.Column('vms_mb', sa.Float(), nullable=False),
    sa.Column('shared_mb', sa.Float(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('peak_rss_mb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_monitor'
    )
    op.create_index('idx_memory_snapshots_app_ts', 'memory_snapshots', ['app_name', 'captured_at'], unique=False, schema='app_monitor')
    op.create_index('idx_memory_snapshots_ts', 'memory_snapshots', ['captured_at'], unique=False, schema='app_monitor')
    op.create_index(op.f('ix_app_monitor_memory_snapshots_app_name'), 'memory_snapshots', ['app_name'], unique=False, schema='app_monitor')
    op.create_table('request_memory_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('rss_before_mb', sa.Float(), nullable=False),
    sa.Column('rss_after_mb', sa.Float(), nullable=False),
    sa.Column('rss_delta_mb', sa.Float(), nullable=False),
    sa.Column('peak_during_mb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_monitor'
    )
    op.create_index('idx_req_mem_app_ts', 'request_memory_stats', ['app_name', 'captured_at'], unique=False, schema='app_monitor')
    op.create_index('idx_req_mem_heavy', 'request_memory_stats', ['rss_delta_mb'], unique=False, schema='app_monitor')
    op.create_index(op.f('ix_app_monitor_request_memory_stats_app_name'), 'request_memory_stats', ['app_name'], unique=False, schema='app_monitor')
    op.create_table('texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_text_dup_check'
    )
    op.create_index(op.f('ix_app_text_dup_check_texts_code'), 'texts', ['code'], unique=False, schema='app_text_dup_check')
    op.create_index(op.f('ix_app_text_dup_check_texts_content'), 'texts', ['content'], unique=False, schema='app_text_dup_check')
    op.create_table('auth_rate_limits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_users'
    )
    op.create_index(op.f('ix_app_users_auth_rate_limits_created_at'), 'auth_rate_limits', ['created_at'], unique=False, schema='app_users')
    op.create_index(op.f('ix_app_users_auth_rate_limits_identifier'), 'auth_rate_limits', ['identifier'], unique=False, schema='app_users')
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app_users'
    )
    op.create_table('auth_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_users'
    )
    op.create_index(op.f('ix_app_users_auth_users_email'), 'auth_users', ['email'], unique=True, schema='app_users')
    op.create_index(op.f('ix_app_users_auth_users_username'), 'auth_users', ['username'], unique=True, schema='app_users')
    op.create_table('service_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['app_data_registry.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'version_number', name='uq_service_version'),
    schema='app_data_registry'
    )
    op.create_index('idx_service_version_active', 'service_versions', ['service_id', 'is_active'], unique=False, schema='app_data_registry')
    op.create_table('group_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['app_ecomru.processing_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'url', name='uq_group_file_url'),
    schema='app_ecomru'
    )
    op.create_index('idx_group_file_status', 'group_files', ['status'], unique=False, schema='app_ecomru')
    op.create_table('auth_email_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_users'
    )
    op.create_index(op.f('ix_app_users_auth_email_tokens_expires_at'), 'auth_email_tokens', ['expires_at'], unique=False, schema='app_users')
    op.create_index(op.f('ix_app_users_auth_email_tokens_purpose'), 'auth_email_tokens', ['purpose'], unique=False, schema='app_users')
    op.create_index(op.f('ix_app_users_auth_email_tokens_token'), 'auth_email_tokens', ['token'], unique=True, schema='app_users')
    op.create_index(op.f('ix_app_users_auth_email_tokens_user_id'), 'auth_email_tokens', ['user_id'], unique=False, schema='app_users')
    op.create_table('auth_refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_users'
    )
    op.create_index(op.f('ix_app_users_auth_refresh_tokens_expires_at'), 'auth_refresh_tokens', ['expires_at'], unique=False, schema='app_users')
    op.create_index(op.f('ix_app_users_auth_refresh_tokens_token'), 'auth_refresh_tokens', ['token'], unique=True, schema='app_users')
    op.create_index(op.f('ix_app_users_auth_refresh_tokens_user_id'), 'auth_refresh_tokens', ['user_id'], unique=False, schema='app_users')
    op.create_table('auth_user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['app_users.auth_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', 'id'),
    schema='app_users'
    )
    op.create_table('login_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_users'
    )
    op.create_index(op.f('ix_app_users_login_stats_login_at'), 'login_stats', ['login_at'], unique=False, schema='app_users')
    op.create_index(op.f('ix_app_users_login_stats_success'), 'login_stats', ['success'], unique=False, schema='app_users')
    op.create_index(op.f('ix_app_users_login_stats_user_id'), 'login_stats', ['user_id'], unique=False, schema='app_users')
    op.create_table('version_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['app_data_registry.data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['app_data_registry.service_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'source_id', name='uq_version_source'),
    schema='app_data_registry'
    )
    op.create_index('idx_source_versions', 'version_sources', ['source_id'], unique=False, schema='app_data_registry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_versions', table_name='version_sources', schema='app_data_registry')
    op.drop_table('version_sources', schema='app_data_registry')
    op.drop_index(op.f('ix_app_users_login_stats_user_id'), table_name='login_stats', schema='app_users')
    op.drop_index(op.f('ix_app_users_login_stats_success'), table_name='login_stats', schema='app_users')
    op.drop_index(op.f('ix_app_users_login_stats_login_at'), table_name='login_stats', schema='app_users')
    op.drop_table('login_stats', schema='app_users')
    op.drop_table('auth_user_roles', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_refresh_tokens_user_id'), table_name='auth_refresh_tokens', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_refresh_tokens_token'), table_name='auth_refresh_tokens', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_refresh_tokens_expires_at'), table_name='auth_refresh_tokens', schema='app_users')
    op.drop_table('auth_refresh_tokens', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_email_tokens_user_id'), table_name='auth_email_tokens', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_email_tokens_token'), table_name='auth_email_tokens', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_email_tokens_purpose'), table_name='auth_email_tokens', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_email_tokens_expires_at'), table_name='auth_email_tokens', schema='app_users')
    op.drop_table('auth_email_tokens', schema='app_users')
    op.drop_index('idx_group_file_status', table_name='group_files', schema='app_ecomru')
    op.drop_table('group_files', schema='app_ecomru')
    op.drop_index('idx_service_version_active', table_name='service_versions', schema='app_data_registry')
    op.drop_table('service_versions', schema='app_data_registry')
    op.drop_index(op.f('ix_app_users_auth_users_username'), table_name='auth_users', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_users_email'), table_name='auth_users', schema='app_users')
    op.drop_table('auth_users', schema='app_users')
    op.drop_table('auth_roles', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_rate_limits_identifier'), table_name='auth_rate_limits', schema='app_users')
    op.drop_index(op.f('ix_app_users_auth_rate_limits_created_at'), table_name='auth_rate_limits', schema='app_users')
    op.drop_table('auth_rate_limits', schema='app_users')
    op.drop_index(op.f('ix_app_text_dup_check_texts_content'), table_name='texts', schema='app_text_dup_check')
    op.drop_index(op.f('ix_app_text_dup_check_texts_code'), table_name='texts', schema='app_text_dup_check')
    op.drop_table('texts', schema='app_text_dup_check')
    op.drop_index(op.f('ix_app_monitor_request_memory_stats_app_name'), table_name='request_memory_stats', schema='app_monitor')
    op.drop_index('idx_req_mem_heavy', table_name='request_memory_stats', schema='app_monitor')
    op.drop_index('idx_req_mem_app_ts', table_name='request_memory_stats', schema='app_monitor')
    op.drop_table('request_memory_stats', schema='app_monitor')
    op.drop_index(op.f('ix_app_monitor_memory_snapshots_app_name'), table_name='memory_snapshots', schema='app_monitor')
    op.drop_index('idx_memory_snapshots_ts', table_name='memory_snapshots', schema='app_monitor')
    op.drop_index('idx_memory_snapshots_app_ts', table_name='memory_snapshots', schema='app_monitor')
    op.drop_table('memory_snapshots', schema='app_monitor')
    op.drop_index(op.f('ix_app_monitor_memory_alerts_app_name'), table_name='memory_alerts', schema='app_monitor')
    op.drop_index('idx_mem_alerts_ts', table_name='memory_alerts', schema='app_monitor')
    op.drop_index('idx_mem_alerts_app_level', table_name='memory_alerts', schema='app_monitor')
    op.drop_table('memory_alerts', schema='app_monitor')
    op.drop_index(op.f('ix_app_mail_mail_tasks_to_email'), table_name='mail_tasks', schema='app_mail')
    op.drop_index(op.f('ix_app_mail_mail_tasks_task_id'), table_name='mail_tasks', schema='app_mail')
    op.drop_index(op.f('ix_app_mail_mail_tasks_status'), table_name='mail_tasks', schema='app_mail')
    op.drop_table('mail_tasks', schema='app_mail')
    op.drop_index('idx_links_url_normalized', table_name='links', schema='app_link')
    op.drop_index('idx_links_url_hash', table_name='links', schema='app_link')
    op.drop_table('links', schema='app_link')
    op.drop_table('schema_extraction_log', schema='app_file_manager')
    op.drop_table('file_download_log', schema='app_file_manager')
    op.drop_index(op.f('ix_app_ecomru_processing_groups_status'), table_name='processing_groups', schema='app_ecomru')
    op.drop_index(op.f('ix_app_ecomru_processing_groups_entity'), table_name='processing_groups', schema='app_ecomru')
    op.drop_table('processing_groups', schema='app_ecomru')
    op.drop_index(op.f('ix_app_ecomru_notification_log_entity'), table_name='notification_log', schema='app_ecomru')
    op.drop_index('idx_notification_log_lookup', table_name='notification_log', schema='app_ecomru')
    op.drop_table('notification_log', schema='app_ecomru')
    op.drop_index('idx_downloaded_status', table_name='downloaded_files', schema='app_ecomru')
    op.drop_table('downloaded_files', schema='app_ecomru')
    op.drop_table('dim_data_sets_verified', schema='app_datasets')
    op.drop_index(op.f('ix_app_data_registry_services_name'), table_name='services', schema='app_data_registry')
    op.drop_table('services', schema='app_data_registry')
    op.drop_index(op.f('ix_app_data_registry_data_sources_name'), table_name='data_sources', schema='app_data_registry')
    op.drop_table('data_sources', schema='app_data_registry')
    # ### end Alembic commands ###